// <auto-generated />
using ConnectWithEfCore.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectWithEfCore.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ConnectWithEfCore.Models.Data.Wand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Wand", (string)null);
                });

            modelBuilder.Entity("ConnectWithEfCore.Models.Data.Wizard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wizard", (string)null);
                });

            modelBuilder.Entity("WandWizard", b =>
                {
                    b.Property<int>("WandsId")
                        .HasColumnType("int");

                    b.Property<int>("WizardsId")
                        .HasColumnType("int");

                    b.HasKey("WandsId", "WizardsId");

                    b.HasIndex("WizardsId");

                    b.ToTable("WandWizard");
                });

            modelBuilder.Entity("WandWizard", b =>
                {
                    b.HasOne("ConnectWithEfCore.Models.Data.Wand", null)
                        .WithMany()
                        .HasForeignKey("WandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConnectWithEfCore.Models.Data.Wizard", null)
                        .WithMany()
                        .HasForeignKey("WizardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
